
[renderd]
pid_file=/home/nlevisrael/gits/osm/inner-system/run/renderd/renderd.pid
stats_file=/home/nlevisrael/gits/osm/inner-system/run/renderd/renderd.stats
socketname=/home/nlevisrael/gits/osm/inner-system/run/renderd/renderd.sock
num_threads=1
tile_dir=/home/nlevisrael/gits/osm/inner-system/var/cache/renderd/tiles

[mapnik]
plugins_dir=/home/nlevisrael/gits/osm/mapnik-git/mapnik/-run-cmake_/install/lib/mapnik/input
font_dir=/usr/share/fonts/truetype
font_dir_recurse=true


