[renderd]
socketname=/home/nlevisrael/gits/osm/inner-system/var/run/renderd/renderd.sock
num_threads=4
tile_dir=/home/nlevisrael/gits/osm/inner-system/var/lib/mod_tile
stats_file=/home/nlevisrael/gits/osm/inner-system/var/run/renderd/renderd.stats

[mapnik]
plugins_dir=/home/nlevisrael/gits/osm/inner-system/usr/lib/mapnik/3.0/input
font_dir=/home/nlevisrael/gits/osm/inner-system/usr/share/fonts/truetype/ttf-dejavu
font_dir_recurse=1

[default]
URI=/osm_tiles/
TILEDIR=/home/nlevisrael/gits/osm/inner-system/var/lib/mod_tile
XML=/home/nlevisrael/gits/osm/inner-system/usr/share/mapnik/openstreetmap-carto/style.xml
HOST=localhost
TILESIZE=256
MAXZOOM=19

